server:
  port: 8081
spring:
  config:
    name: dev
---
server:
  port: 8082
spring:
  config:
    name: pro
---
server:
  port: 8083
spring:
  config:
    name: test
---
spring:
  config:
    activate:
      on-profile: test