spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.184.97:3306/springboot2023
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml
