#server:
#  port: 8082
name: zhangsan

#对象
person:
  name: wangwu #${name}
  age: 20

person2: {name: lisi, age: 20}

#数组
address:
  - beijing
  - shanghai

address2: [beijing, shanghai]

#纯量
msg1: 'hello \n world' #不会识别转义字符，会原样输出
msg2: "hello \n world" #会识别转义字符

